[package]
name = "dircpy"
version = "0.3.1"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Copy directories recursively with flexible options."
repository = "https://github.com/woelper/dircpy/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
log = "0.4.11"


[dev-dependencies]
unzip = "0.1.0"
reqwest = { version = "0.10.8", features = ["blocking"] }