[package]
name = "dircpy"
version = "0.3.4"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Copy directories recursively with flexible options."
repository = "https://github.com/woelper/dircpy/"
keywords = ["copy", "recursive", "filesystem", "file"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
log = "0.4.11"
rayon = "1.4.0"

[dev-dependencies]
unzip = "0.1.0"
reqwest = { version = "0.10.8", features = ["blocking"] }
env_logger = "0.7.1"
criterion = "0.3"

[[bench]]
name = "copy_rustlang"
harness = false