on: [push]

name: cargo check linux

jobs:
  check:
    name: Check Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  check:
    name: Check Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check