on: [push]

name: Test Windows

jobs:
  check:
    name: Test windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check